{{- if and (not .Values.app.existingSecret) .Values.app.sharedPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-quiz.fullname" . }}
  labels:
    {{- include "team-quiz.labels" . | nindent 4 }}
type: Opaque
stringData:
  shared-password: {{ .Values.app.sharedPassword | quote }}
{{- end }}
