{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "team-quiz.serviceAccountName" . }}
  labels:
    {{- include "team-quiz.labels" . | nindent 4 }}
{{- end }}
