#!/usr/bin/env python3
"""Builds the question sets into questions/<id>.json.
# NOTE: the questions/*.json files are the CANONICAL source. Several sets have been
# length/position-debiased directly in the JSON; regenerating from this script would
# revert that content. Edit the JSON files, or update the rows here first.

Each set file: { id, name, description, order, questions: [ {id, topic, text, options, correct, explanation} ] }
- Core is bootstrapped from the existing questions.json (or re-read from its own set file).
- Advanced and AI Foundations are defined inline below.
Edit a set by editing its JSON file directly; this script is just how they were created.
"""
import json, os, random

HERE = os.path.dirname(os.path.abspath(__file__))
QDIR = os.path.join(HERE, "questions")
os.makedirs(QDIR, exist_ok=True)


def load_core_questions():
    # Prefer the already-split set file; fall back to the legacy questions.json
    for path in [os.path.join(QDIR, "java-devops-core.json"), os.path.join(HERE, "questions.json")]:
        if os.path.exists(path):
            data = json.load(open(path))
            return data["questions"] if isinstance(data, dict) else data
    raise SystemExit("No core questions source found")


# -------- Advanced (topic, text, options, correct, explanation) --------
ADVANCED = [
("Java", "A mutable object is used as a HashMap key, then one of its fields changes after insertion. What happens?",
 ["Nothing, keys are copied", "You may no longer be able to retrieve the entry", "The map re-sorts itself", "It throws immediately"], 1,
 "The key's hashCode changes, so it lands in a different bucket than where it was stored — the entry becomes effectively unreachable. Keys must be effectively immutable."),
("Java", "Under high contention, why does ConcurrentHashMap usually outperform Collections.synchronizedMap?",
 ["It skips locking entirely", "It locks at a finer granularity, allowing concurrent access to different buckets", "It is single-threaded", "It caches everything"], 1,
 "synchronizedMap serialises every operation on one lock; ConcurrentHashMap locks per-bucket/segment, so unrelated updates proceed in parallel."),
("Java", "For a double-checked-locking singleton to be correct, the instance field must be…",
 ["static only", "volatile", "final", "transient"], 1,
 "Without volatile another thread can observe a non-null but partially-constructed instance due to reordering."),
("Java", "Two threads increment a shared 'volatile int' with i++. Is it safe?",
 ["Yes, volatile makes it atomic", "No — volatile gives visibility but not atomicity; use AtomicInteger", "Yes, ints are always atomic", "Only on 64-bit JVMs"], 1,
 "i++ is read-modify-write, three steps. volatile ensures visibility of the latest value but doesn't make the compound operation atomic."),
("Java", "A fixed thread pool backed by an unbounded queue is hammered with tasks faster than it can process. Risk?",
 ["Nothing", "The queue grows until the JVM runs out of memory", "Threads multiply automatically", "Tasks are dropped silently"], 1,
 "An unbounded queue accepts work indefinitely; without backpressure or a bounded queue, memory is exhausted."),
("Java", "Integer a=127,b=127 gives a==b true, but a=128,b=128 gives a==b false. Why?",
 ["A JVM bug", "Integers -128..127 are cached, so == compares the same object; outside that range they're distinct objects", "128 overflows", "Autoboxing is random"], 1,
 "The Integer cache reuses instances for -128..127. Always compare boxed values with equals, not ==."),
("Java", "A static collection keeps accumulating entries that are never removed. This is a classic…",
 ["Performance win", "Memory leak — objects stay reachable via the static reference", "Deadlock", "Race condition"], 1,
 "Static references live for the app's lifetime, so anything they hold can never be garbage-collected."),
("Java", "In try-with-resources, if the body throws and close() also throws, what happens to the close() exception?",
 ["It replaces the original", "It is suppressed and attached to the primary exception (getSuppressed())", "It is lost silently", "Both are thrown separately"], 1,
 "The primary exception propagates; the close() exception is added to its suppressed list so nothing is lost."),
("Java", "Which set of properties makes a class properly immutable?",
 ["Just private fields", "No subclass mutation, private final fields, no setters, and defensive copies of mutable in/out", "Only a final class", "Synchronized getters"], 1,
 "Immutability needs all of these; a leaked reference to an internal mutable field breaks it even if fields are final."),
("Java", "A parallel stream appends results into a shared ArrayList. What's wrong?",
 ["Nothing", "ArrayList isn't thread-safe — concurrent adds corrupt it; use a proper collector/reduction", "Parallel streams are always slower", "It won't compile"], 1,
 "Side-effecting shared mutable state from parallel streams causes races; use collect() with a concurrent-safe collector or a reduction."),
("Java", "Calling Optional.get() without checking presence is discouraged because…",
 ["It's deprecated", "It throws NoSuchElementException when empty — defeating Optional's purpose", "It's slow", "It returns null"], 1,
 "The point of Optional is to force handling the empty case; blind get() reintroduces the null-style crash. Prefer orElse/ifPresent/map."),
("Java", "You override equals() but not hashCode(), then store the object in a HashSet and look it up. Result?",
 ["Always found", "May not be found — equal objects can have different hash codes", "Compile error", "The set becomes ordered"], 1,
 "Hash-based collections locate objects by hashCode first; violating the equals/hashCode contract breaks lookups."),
("Java", "A Comparator inconsistent with equals is used in a TreeSet. Consequence?",
 ["Faster sorting", "Elements the comparator deems equal are treated as duplicates and dropped/merged", "It throws", "Nothing"], 1,
 "Sorted sets/maps use the comparator (not equals) for identity, so 'compare == 0' elements collapse together."),
("Java", "A ThreadLocal is set but never removed on a pooled thread. Risk?",
 ["Nothing", "Leaked state/memory carried into unrelated tasks reusing that thread", "Deadlock", "The pool shrinks"], 1,
 "Pool threads are reused, so a lingering ThreadLocal leaks data across tasks and can retain memory. Always remove() in a finally."),
("Java", "Throwing a checked exception from inside a standard Stream map() lambda…",
 ["Works fine", "Won't compile — you must catch or wrap it", "Silently ignored", "Converts to unchecked automatically"], 1,
 "The built-in functional interfaces don't declare checked exceptions, so you must handle or wrap them inside the lambda."),
("Java", "thenApply vs thenCompose on CompletableFuture — when do you need thenCompose?",
 ["Never", "When your function itself returns a CompletableFuture, to avoid a nested future", "Only for logging", "They're identical"], 1,
 "thenCompose flattens a future-returning function (like flatMap); thenApply would give you a CompletableFuture<CompletableFuture<...>>."),
("DevOps", "A pod sets cpu and memory requests equal to its limits. Its QoS class is…",
 ["BestEffort", "Guaranteed", "Burstable", "Preemptible"], 1,
 "requests == limits for all resources gives Guaranteed QoS, which is evicted last under pressure."),
("DevOps", "Under node memory pressure, which pods does the kubelet evict first?",
 ["Guaranteed", "BestEffort (no requests), then Burstable, then Guaranteed", "Random", "The newest"], 1,
 "Eviction follows QoS: BestEffort first, Guaranteed last, so critical guaranteed workloads survive longest."),
("DevOps", "What does a PodDisruptionBudget protect against?",
 ["Node failures", "Too many pods of an app going down at once during voluntary disruptions like drains/upgrades", "Image pull errors", "Bad YAML"], 1,
 "A PDB caps how many replicas can be voluntarily taken down simultaneously, preserving availability during maintenance."),
("DevOps", "maxUnavailable and maxSurge in a Deployment control…",
 ["Resource limits", "How many pods may be unavailable or added above desired during a rolling update", "Replica count", "Probe timing"], 1,
 "They tune rollout speed vs availability: surge adds temporary extra pods, unavailable allows some to be down."),
("DevOps", "When is a StatefulSet the right choice over a Deployment?",
 ["Always", "When you need stable network identities and stable per-pod persistent storage", "For stateless web apps", "To save memory"], 1,
 "StatefulSets give ordered, stable pod identities and sticky volumes — needed by databases and clustered stores."),
("DevOps", "A headless Service (clusterIP: None) provides…",
 ["A single virtual IP", "Per-pod DNS records for addressing individual pods directly", "External load balancing", "TLS termination"], 1,
 "Without a cluster IP, DNS returns each pod's address, which is how StatefulSet members find each other."),
("DevOps", "Why does Terraform use state locking (e.g. via DynamoDB)?",
 ["To speed up plans", "To stop concurrent applies from corrupting the shared state", "To encrypt state", "To store secrets"], 1,
 "A lock ensures only one apply mutates state at a time; concurrent writes could leave state inconsistent with reality."),
("DevOps", "Why prefer for_each over count for a set of named resources in Terraform?",
 ["It's newer", "Stable addressing by key — removing one item doesn't reindex and recreate the others", "It's faster", "count can't make multiples"], 1,
 "count addresses by position, so deleting the middle item shifts indices and forces recreation; for_each keys are stable."),
("DevOps", "Why COPY package.json and install deps before COPY of the source in a Dockerfile?",
 ["Style only", "Layer caching — dependencies aren't reinstalled when only application source changes", "It's required", "To shrink the base image"], 1,
 "Ordering stable steps first lets Docker reuse the cached dependency layer across builds where only code changed."),
("DevOps", "A key advantage of a canary release over blue-green?",
 ["No extra infra", "Gradual exposure to a small subset, limiting blast radius and enabling metric-based rollout", "Instant full switch", "No monitoring needed"], 1,
 "Canary shifts a slice of traffic first so you can watch metrics and abort before everyone is affected."),
("DevOps", "With at-least-once message delivery, consumers must be…",
 ["Stateless", "Idempotent — able to handle duplicate deliveries safely", "Single-threaded", "Faster than producers"], 1,
 "At-least-once can redeliver, so processing the same message twice must not double-apply effects."),
("DevOps", "A Horizontal Pod Autoscaler scales replicas based on…",
 ["Time of day", "Observed metrics (e.g. CPU or custom) compared to a target", "Node count", "Image size"], 1,
 "The HPA adjusts replica count to keep the measured metric near the target you set."),
("DevOps", "TLS is terminated at the load balancer. Traffic from the LB to the backend is then…",
 ["Always encrypted", "Unencrypted unless you re-encrypt — consider end-to-end TLS for sensitive data", "Compressed", "Cached"], 1,
 "Termination decrypts at the edge; the hop to the backend is plaintext unless you explicitly re-encrypt it."),
("DevOps", "During a planned failover, a very high DNS TTL causes…",
 ["Instant cutover", "Clients keep using the old IP until their caches expire — lower TTL beforehand", "Nothing", "DNS to fail"], 1,
 "Caches honour the TTL, so a long TTL delays the switch. Reduce TTL ahead of a planned change."),
("DevOps", "A pod's readiness probe fails but liveness passes. What happens?",
 ["It's restarted", "It keeps running but is removed from Service endpoints, so it gets no traffic", "It's deleted", "Nothing changes"], 1,
 "Readiness gates traffic without restarting; the pod stays up but is taken out of the load-balancing rotation."),
("DevOps", "In immutable infrastructure, how do you 'fix' a misbehaving server?",
 ["SSH in and patch it", "Replace it with a fresh instance from a known-good image", "Edit files in place", "Reboot repeatedly"], 1,
 "Immutable infra replaces rather than mutates, so servers stay reproducible and free of configuration drift."),
("DevOps", "A non-idempotent deploy step is retried by CI after a timeout. Risk?",
 ["Faster deploy", "Duplicate or partial side effects — make operations idempotent so retries are safe", "Nothing", "It rolls back automatically"], 1,
 "If the first attempt partly succeeded, a blind retry can double-apply; idempotency makes retries harmless."),
]

# -------- AI Foundations · Beginner --------
AI = [
("AI", "How does machine learning differ from traditional programming?",
 ["It runs faster", "The system learns patterns from data instead of following hand-written rules", "It needs no computer", "It never makes mistakes"], 1,
 "In ML you provide examples and the model infers the rules, rather than a developer coding every rule explicitly."),
("AI", "Supervised learning is trained on…",
 ["Unlabelled data", "Labelled examples — inputs paired with known correct outputs", "No data", "Only images"], 1,
 "The model learns to map inputs to outputs from examples where the answer is already known."),
("AI", "Unsupervised learning works on…",
 ["Labelled data", "Unlabelled data, finding structure or groupings on its own", "Only numbers", "Human feedback"], 1,
 "With no labels, it discovers patterns such as clusters or associations in the data."),
("AI", "'Training' a model means…",
 ["Running it in production", "Adjusting it on data so it gets better at a task", "Deleting old data", "Writing documentation"], 1,
 "Training tunes the model's internal parameters to reduce its error on the training data."),
("AI", "'Inference' refers to…",
 ["Collecting data", "Using a trained model to make predictions on new input", "Labelling data", "Cleaning data"], 1,
 "Inference is the model doing its job on fresh, unseen inputs after training is done."),
("AI", "Overfitting is when a model…",
 ["Trains too little", "Fits the training data too closely and generalises poorly to new data", "Runs out of memory", "Has too few parameters"], 1,
 "An overfit model has essentially memorised the training set, so it performs badly on data it hasn't seen."),
("AI", "Why split data into training and test sets?",
 ["To save space", "To honestly estimate how the model performs on unseen data", "To train twice", "It's optional"], 1,
 "Evaluating on held-out data prevents you from being fooled by performance on examples the model already learned."),
("AI", "Classification vs regression?",
 ["No difference", "Classification predicts categories; regression predicts continuous numbers", "Regression predicts labels", "Both predict text"], 1,
 "Predicting 'spam/not spam' is classification; predicting a house price is regression."),
("AI", "A 'feature' is…",
 ["The final answer", "An input variable the model uses to make a prediction", "A bug", "The training loop"], 1,
 "Features are the measurable inputs (e.g. age, pixels, words) the model bases its output on."),
("AI", "At its core, a large language model…",
 ["Looks answers up in a database", "Predicts the likely next tokens of text", "Understands like a human", "Only does maths"], 1,
 "An LLM is trained to continue text by predicting the most probable next token given what came before."),
("AI", "A 'token' is…",
 ["A password", "A chunk of text (a word or subword) the model processes", "A GPU", "A dataset"], 1,
 "Models break text into tokens; both input length and output are measured in tokens."),
("AI", "An LLM 'hallucination' is…",
 ["A crash", "Confident output that is factually wrong or made up", "A slow response", "A type of GPU"], 1,
 "Models can produce fluent, plausible-sounding text that isn't true — always verify important facts."),
("AI", "Why can biased training data be a problem?",
 ["It trains faster", "The model learns and can amplify that bias in its outputs", "It uses less memory", "It has no effect"], 1,
 "A model reflects its data; skewed or unfair data leads to skewed or unfair predictions."),
("AI", "'Garbage in, garbage out' in ML means…",
 ["Models delete bad data", "Poor-quality data leads to a poor model", "Output is always garbage", "Data doesn't matter"], 1,
 "Model quality is bounded by data quality; noisy or wrong data produces an unreliable model."),
("AI", "Fine-tuning a model means…",
 ["Building it from scratch", "Further training a pretrained model on task-specific data", "Deleting parameters", "Running inference"], 1,
 "Fine-tuning adapts an existing general model to a narrower task or domain with additional training."),
("AI", "A model's 'parameters' are…",
 ["Its input files", "The learned weights adjusted during training", "The prompts", "The hardware"], 1,
 "Parameters are the numbers the model learns; large models have billions of them."),
("AI", "Why are GPUs commonly used for ML?",
 ["They're cheaper", "They perform the parallel matrix maths far faster than CPUs", "They store more data", "They're required by law"], 1,
 "Training and inference are mostly large matrix operations, which GPUs execute massively in parallel."),
("AI", "An 'embedding' represents data as…",
 ["A single number", "A vector that captures meaning and similarity", "A password", "An image"], 1,
 "Embeddings map items into a vector space where similar things sit close together, enabling search and comparison."),
("AI", "Why is accuracy alone misleading on imbalanced data?",
 ["It always is wrong", "A model can score high by just predicting the majority class", "Accuracy is illegal", "It needs a GPU"], 1,
 "If 99% of cases are negative, always predicting 'negative' scores 99% while catching nothing useful."),
("AI", "'Human in the loop' means…",
 ["No automation", "People review or approve the model's outputs", "The model has feelings", "Training by hand"], 1,
 "Keeping a human checkpoint helps catch errors and handle high-stakes or ambiguous decisions."),
("AI", "An LLM's 'context window' is…",
 ["Its accuracy", "How much text it can consider at once", "Its price", "The GPU size"], 1,
 "The context window limits how much prompt and conversation the model can take into account in one go."),
("AI", "Increasing the 'temperature' when generating text tends to…",
 ["Make it faster", "Make the output more random and varied", "Improve accuracy", "Reduce cost"], 1,
 "Higher temperature increases randomness; lower temperature makes output more focused and deterministic."),
("AI", "Why validate AI-generated code before running it?",
 ["It's always perfect", "It can be subtly wrong or insecure despite looking correct", "To slow down", "It never compiles"], 1,
 "Generated code may contain bugs or vulnerabilities that read plausibly — review and test it like any code."),
("AI", "Why is pasting secrets or customer data into an external AI tool risky?",
 ["It's slow", "The data leaves your control and may be stored or exposed", "It costs more", "It improves the model for you"], 1,
 "Sensitive data sent to a third party may be retained or leaked; follow your org's data-handling rules."),
("AI", "Bigger models usually trade off…",
 ["Nothing", "Higher cost and latency for potentially better quality", "Accuracy for speed always", "Data for hardware"], 1,
 "Larger models can be more capable but cost more and respond slower; pick the right size for the job."),
("AI", "LLM outputs are…",
 ["Always identical", "Probabilistic — the same prompt can produce different answers", "Random noise", "Pre-written"], 1,
 "Generation samples from probabilities, so responses can vary run to run unless settings force determinism."),
("AI", "A 'prompt' is…",
 ["The model's answer", "The input or instructions you give the model", "A training set", "A GPU"], 1,
 "The prompt is what you send in; clear, specific prompts generally get better results."),
("AI", "Retrieval-augmented generation (RAG) helps by…",
 ["Making the model bigger", "Supplying relevant external documents to ground the answer", "Removing the prompt", "Training from scratch"], 1,
 "RAG fetches relevant text and feeds it to the model so answers can cite up-to-date, specific sources."),
("AI", "Reinforcement learning trains an agent using…",
 ["Labelled images", "Rewards and penalties from its actions", "No data at all", "Only human text"], 1,
 "The agent learns a strategy by trying actions and being rewarded for good outcomes."),
("AI", "Saying a model is 'not sentient' means it…",
 ["Is broken", "Produces patterns learned from data, without understanding or intent", "Can't run", "Is offline"], 1,
 "However fluent, the model has no beliefs or awareness; it's statistical pattern completion."),
("AI", "When are simple hand-written rules often better than ML?",
 ["Never", "When the logic is well-defined and stable, so ML adds needless complexity and uncertainty", "Always", "Only for images"], 1,
 "If you can state the rules exactly, code them — ML shines when patterns are complex or hard to specify."),
("AI", "Why is transparency/explainability valued in AI decisions?",
 ["It's faster", "So outcomes can be understood, trusted, and challenged", "It reduces cost", "It's required for GPUs"], 1,
 "Especially for decisions affecting people, being able to explain why a model decided something supports trust and accountability."),
]


GIT = [
("Git", "Why create a feature branch instead of committing straight to main?",
 ["To hide your work", "To isolate changes until they're reviewed and ready to merge", "To delete history", "To make the repo private"], 1,
 "Branches let you develop safely without destabilising main, and merge only after review."),
("Git", "Why avoid rebasing a branch others have already pulled?",
 ["Rebase is slow", "It rewrites shared history and breaks everyone else's copies", "It deletes files", "It's not allowed"], 1,
 "Rebasing changes commit hashes; on shared branches that forces painful reconciliation for collaborators. Rebase local/private work only."),
("Git", "What's the safest way to undo a bad commit that's already on a shared branch?",
 ["git reset --hard", "git revert (adds a new commit that undoes it)", "delete the branch", "git commit --amend"], 1,
 "revert preserves history by adding an inverse commit, so it doesn't rewrite what others have pulled."),
("Git", "git fetch vs git pull?",
 ["They're identical", "fetch downloads remote changes; pull is fetch plus merge into your branch", "pull only downloads", "fetch merges automatically"], 1,
 "fetch updates your remote-tracking refs without touching your working branch; pull also merges them in."),
("Git", "What is git stash for?",
 ["Deleting changes", "Temporarily shelving uncommitted changes so you can switch context", "Pushing to remote", "Tagging a release"], 1,
 "stash saves your work-in-progress off to the side so you can e.g. switch branches, then reapply it later."),
("Git", "git cherry-pick does what?",
 ["Merges two branches", "Applies a specific commit onto your current branch", "Deletes a commit", "Renames a branch"], 1,
 "cherry-pick copies one commit's changes onto where you are now — handy for pulling a single fix across branches."),
("Git", "You're mid-merge and see <<<<<<<, =======, >>>>>>> in a file. What are they?",
 ["Syntax errors", "Conflict markers showing your changes vs theirs to resolve manually", "Comments", "Encryption"], 1,
 "Git inserts these markers where two branches changed the same lines; you edit to the desired result and remove them."),
("Git", "Why is `git push --force` dangerous, and what's safer?",
 ["It's fine", "It can overwrite others' commits; use --force-with-lease which refuses if the remote moved", "It deletes the repo", "Nothing is safer"], 1,
 "--force clobbers remote history blindly; --force-with-lease only pushes if no one else has pushed since you last fetched."),
("Git", "git bisect helps you…",
 ["Split a file", "Binary-search commit history to find the one that introduced a bug", "Merge branches", "Compress the repo"], 1,
 "You mark a known-good and known-bad commit and bisect checks out midpoints so you find the culprit in log(n) steps."),
("Git", "What does trunk-based development favour?",
 ["Long-lived branches", "Short-lived branches merged to main frequently", "No branches ever", "One branch per developer forever"], 1,
 "Frequent small merges to a single trunk reduce merge pain and keep everyone integrated."),
("Git", "A 'squash merge' does what to a PR's commits?",
 ["Deletes them", "Combines them into a single commit on the target branch", "Reverts them", "Duplicates them"], 1,
 "Squashing collapses the PR's many small commits into one clean commit in history."),
("Git", "You committed an AWS key by mistake. What must you do?",
 ["Delete it in a new commit", "Rotate/revoke the key — it remains in history", "Make the repo private", "Nothing"], 1,
 "The secret is compromised and still recoverable from history; rotating it is the real fix, scrubbing history is secondary."),
("Git", "git reset --soft vs --hard?",
 ["No difference", "--soft keeps your changes staged; --hard discards them entirely", "--soft deletes files", "--hard keeps changes"], 1,
 "Use --soft to move the branch pointer while keeping work; --hard throws changes away, so use it carefully."),
("Git", "What is a fast-forward merge?",
 ["A merge with conflicts", "Moving the branch pointer forward when there's no divergence, with no merge commit", "A forced push", "A rebase"], 1,
 "If the target hasn't diverged, Git just advances the pointer to your commits — no separate merge commit needed."),
("Git", "Why keep pull requests small?",
 ["To commit less", "They're easier and faster to review well", "Git requires it", "To avoid tests"], 1,
 "Large PRs get shallow reviews; small, focused ones get real scrutiny and merge faster."),
("Git", "git blame shows…",
 ["Who to fire", "Which commit and author last changed each line", "The build status", "Merge conflicts"], 1,
 "blame annotates lines with their last change — useful for understanding why code is the way it is."),
("Git", "'origin' typically refers to…",
 ["Your first commit", "The default name for the remote you cloned from", "The main branch", "A tag"], 1,
 "origin is just the conventional default name for the primary remote repository."),
("Git", "What do branch protection rules commonly enforce?",
 ["Nothing", "Required reviews and passing checks before merging to a protected branch", "Faster merges", "Automatic deploys"], 1,
 "They stop unreviewed or failing code from reaching important branches like main."),
("Git", "git commit --amend is best avoided when…",
 ["Always", "The commit has already been pushed/shared, since it rewrites history", "You're offline", "The message is long"], 1,
 "Amending changes the commit, so doing it after pushing forces others to reconcile rewritten history."),
("Git", "A good commit message summary line is…",
 ["A full paragraph", "A short, imperative description of the change (e.g. 'Fix null check')", "Just 'update'", "The date"], 1,
 "Concise imperative summaries make history scannable; put the 'why' in the body if needed."),
("Git", "What does git tag typically mark?",
 ["A conflict", "A specific point in history, often a release version", "A branch", "A remote"], 1,
 "Tags label meaningful commits (like v1.2.0) so you can find and check out releases easily."),
("Git", "clone vs fork?",
 ["Same thing", "Clone makes a local copy; fork makes a server-side copy under your own account", "Fork is local", "Clone needs a PR"], 1,
 "You fork someone else's repo to your account (common for contributing), then clone your fork locally."),
("Git", "A 'draft' pull request signals…",
 ["It's merged", "Work in progress, not yet ready to merge", "It's urgent", "It has conflicts"], 1,
 "Draft PRs let you share early for feedback while blocking accidental merges."),
("Git", "Why not commit directly to main in a team repo?",
 ["It's slower", "It bypasses review and CI, risking broken or unvetted code for everyone", "Git forbids it", "It uses more space"], 1,
 "Working through branches and PRs keeps main stable and gives changes a review/CI gate."),
("Git", "An 'atomic' commit means…",
 ["A huge commit", "One logical, self-contained change per commit", "A commit with no message", "A merge commit"], 1,
 "Atomic commits are easier to review, revert, and cherry-pick because each does exactly one thing."),
("Git", "interactive rebase (git rebase -i) lets you…",
 ["Only delete branches", "Reorder, squash, edit or drop commits before sharing them", "Push to remote", "Resolve nothing"], 1,
 "It's a tidy-up tool for local history — combine WIP commits into a clean series before opening a PR."),
]

LINUX = [
("Linux", "Which command changes a file's permissions?",
 ["chown", "chmod", "chgrp", "ls"], 1,
 "chmod sets the read/write/execute bits; chown changes ownership and chgrp changes the group."),
("Linux", "In rwx permissions, what does the 'x' allow for a file?",
 ["Reading", "Executing/running it", "Deleting", "Renaming"], 1,
 "x means execute for files (run it) and, for directories, permission to enter/traverse them."),
("Linux", "What does the pipe '|' do?",
 ["Comments a line", "Sends one command's output as the next command's input", "Redirects to a file", "Runs in background"], 1,
 "Pipes chain commands, e.g. `cat log | grep ERROR` feeds cat's output into grep."),
("Linux", "'>' vs '>>' when redirecting output?",
 ["Same thing", "> overwrites the file; >> appends to it", "> appends", ">> deletes"], 1,
 "Use >> to add to a file without wiping it; > truncates and replaces the contents."),
("Linux", "kill vs kill -9 (SIGKILL)?",
 ["Identical", "Default sends SIGTERM (graceful); -9 forces immediate termination with no cleanup", "-9 is gentler", "kill restarts the process"], 1,
 "Prefer plain kill so the process can shut down cleanly; -9 is a last resort that skips cleanup."),
("Linux", "How do you follow a log file as it grows?",
 ["cat file", "tail -f file", "head file", "less file once"], 1,
 "tail -f streams new lines as they're written — the standard way to watch logs live."),
("Linux", "What does sudo do?",
 ["Deletes files", "Runs a command with elevated (superuser) privileges", "Searches text", "Shows disk usage"], 1,
 "sudo executes a single command as root (or another user), used for privileged operations."),
("Linux", "grep is used to…",
 ["Change permissions", "Search text for lines matching a pattern", "Copy files", "Kill processes"], 1,
 "grep filters input to lines matching a pattern, e.g. finding errors in a log."),
("Linux", "Which shows currently running processes with live CPU/memory usage?",
 ["ls", "top (or htop)", "grep", "cd"], 1,
 "top gives a live view of processes and resource use; ps gives a one-shot snapshot."),
("Linux", "$PATH is…",
 ["Your home directory", "The list of directories the shell searches for executables", "A file", "A permission"], 1,
 "When you type a command, the shell looks through the directories in $PATH to find it."),
("Linux", "df -h vs du?",
 ["Same", "df shows free space per filesystem; du shows space used by files/dirs", "df shows files", "du shows free space"], 1,
 "df answers 'how full is the disk?'; du answers 'what's taking up space here?'."),
("Linux", "An absolute path starts with…",
 ["./", "/ (the filesystem root)", "~", "a letter"], 1,
 "Absolute paths begin at / and are unambiguous; relative paths are interpreted from the current directory."),
("Linux", "What does chmod +x script.sh do?",
 ["Deletes it", "Makes the script executable", "Opens it", "Runs it as root"], 1,
 "It adds the execute bit so you can run the file directly, e.g. ./script.sh."),
("Linux", "The exit code of the last command is in $?. What does 0 mean?",
 ["Failure", "Success", "Permission denied", "Not found"], 1,
 "Convention: 0 means success, any non-zero value signals an error — scripts check this to branch."),
("Linux", "Which safely copies a file to a remote host over SSH?",
 ["cp", "scp (or rsync)", "mv", "cat"], 1,
 "scp uses the SSH connection to copy files between machines; rsync is similar with delta transfers."),
("Linux", "Files beginning with a dot (e.g. .bashrc) are…",
 ["Broken", "Hidden files, not shown by default (use ls -a)", "System-only", "Executables"], 1,
 "Dotfiles are hidden from a normal ls; they usually hold configuration."),
("Linux", "less vs cat for viewing a large file?",
 ["No difference", "less paginates and lets you scroll/search; cat dumps it all at once", "cat paginates", "less edits it"], 1,
 "For big files less is far more usable — you can page through and search without flooding the terminal."),
("Linux", "What does cron do?",
 ["Compresses files", "Runs commands on a schedule", "Kills processes", "Edits text"], 1,
 "cron executes jobs at defined times/intervals — the classic way to schedule recurring tasks."),
("Linux", "stdout vs stderr?",
 ["Same stream", "stdout is normal output; stderr is a separate stream for errors", "stderr is input", "stdout is for errors"], 1,
 "Separating them lets you redirect errors independently, e.g. 2> errors.log."),
("Linux", "rm -rf / would (in principle)…",
 ["Do nothing", "Recursively force-delete everything from root — catastrophic", "List files", "Reboot"], 1,
 "It's the canonical dangerous command; -r recurses, -f forces, and / is everything. Handle with extreme care."),
("Linux", "which command tells you…",
 ["File size", "The path of the executable that would run for a command", "Permissions", "Disk usage"], 1,
 "which resolves a command name to the actual binary found on your $PATH."),
("Linux", "How do you run a long task in the background from the shell?",
 ["Ctrl-C", "Append & to the command", "Type 'bg' first", "Use sudo"], 1,
 "Appending & starts the job in the background; jobs, fg and bg manage it afterwards."),
("Linux", "chown is for…",
 ["Permissions bits", "Changing a file's owner (and optionally group)", "Searching", "Compression"], 1,
 "chown reassigns ownership; combine with chmod to control who can do what."),
("Linux", "man ls does what?",
 ["Runs ls", "Opens the manual page documenting ls", "Deletes ls", "Lists man pages"], 1,
 "man shows built-in documentation for a command — the first place to look for options."),
("Linux", "head vs tail?",
 ["Same", "head shows the first lines of a file; tail shows the last", "head shows last", "tail shows first"], 1,
 "Both default to 10 lines; -n changes the count. tail -f additionally follows a growing file."),
("Linux", "wc -l counts…",
 ["Words", "Lines", "Characters only", "Files"], 1,
 "wc counts lines (-l), words (-w) or bytes/characters (-c) of its input."),
]

AWS = [
("AWS", "Region vs Availability Zone?",
 ["Same thing", "A Region is a geographic area containing multiple isolated AZs (data centres)", "An AZ contains regions", "AZs are global"], 1,
 "You pick a Region (e.g. eu-west-2 London); within it, AZs are separate facilities you spread across for resilience."),
("AWS", "What is IAM for?",
 ["Storage", "Managing identities and their permissions", "Networking", "Monitoring"], 1,
 "IAM controls who (users/roles) can do what on which AWS resources."),
("AWS", "IAM role vs IAM user?",
 ["Same", "A role is assumed temporarily and grants short-lived credentials; a user has long-lived credentials", "A role is a person", "Users can't have policies"], 1,
 "Roles avoid long-lived keys — services and users assume them to get temporary credentials, which is safer."),
("AWS", "S3 is best described as…",
 ["A database", "Object storage for files/blobs", "A virtual server", "A load balancer"], 1,
 "S3 stores objects (files) in buckets, with high durability — not a filesystem or database."),
("AWS", "A security group acts as…",
 ["A user group", "A stateful virtual firewall at the instance level", "A subnet", "A storage volume"], 1,
 "Security groups control inbound/outbound traffic per instance and are stateful (return traffic is allowed automatically)."),
("AWS", "Security group vs network ACL?",
 ["Identical", "SG is stateful and per-instance; NACL is stateless and per-subnet", "Both are per-subnet", "SG is stateless"], 1,
 "NACLs evaluate each direction independently at the subnet boundary; SGs track connections at the instance."),
("AWS", "The shared responsibility model says…",
 ["AWS secures everything", "AWS secures the cloud; you secure what you put in it (data, config, access)", "You secure the hardware", "Security is optional"], 1,
 "AWS handles the underlying infrastructure; configuration, data and access control are your responsibility."),
("AWS", "Why avoid using the root account for daily work?",
 ["It's slower", "It has unrestricted access; a compromise is catastrophic — use IAM users/roles with least privilege", "It costs more", "It can't be used"], 1,
 "Lock the root account away (with MFA) and operate through scoped IAM identities instead."),
("AWS", "What makes a subnet 'public'?",
 ["Its name", "A route to an internet gateway", "Being large", "Having EC2 in it"], 1,
 "A subnet is public if its route table sends internet-bound traffic to an internet gateway; otherwise it's private."),
("AWS", "EC2 is…",
 ["Object storage", "Virtual servers you rent", "A database", "A DNS service"], 1,
 "EC2 provides resizable virtual machines in the cloud."),
("AWS", "A VPC is…",
 ["A virtual machine", "Your isolated virtual network in AWS", "A storage bucket", "A permission"], 1,
 "The VPC is the private network boundary where your resources live, with your own subnets and routing."),
("AWS", "An Elastic IP gives you…",
 ["More storage", "A static public IPv4 address you control", "A firewall", "A DNS name"], 1,
 "Unlike an instance's default public IP, an EIP stays the same and can be remapped between instances."),
("AWS", "Access keys committed to a repo should be…",
 ["Left alone", "Rotated/revoked immediately", "Emailed to the team", "Encrypted in the repo"], 1,
 "Treat leaked keys as compromised: revoke and reissue, and never store keys in code."),
("AWS", "RDS provides…",
 ["Object storage", "Managed relational databases", "Serverless functions", "A CDN"], 1,
 "RDS runs managed engines like PostgreSQL/MySQL, handling patching, backups and failover for you."),
("AWS", "Lambda is…",
 ["A VM", "Serverless functions that run on demand without managing servers", "A database", "A load balancer"], 1,
 "You upload code; Lambda runs it in response to events and you pay per execution, with no servers to manage."),
("AWS", "EBS volumes are…",
 ["Global", "Block storage attached to an EC2 instance, bound to one Availability Zone", "Object storage", "Serverless"], 1,
 "EBS is like a virtual disk for an instance; it lives in a single AZ, which affects where the instance can run."),
("AWS", "What does an Elastic Load Balancer do?",
 ["Stores files", "Distributes incoming traffic across multiple targets", "Runs functions", "Manages IAM"], 1,
 "An ELB spreads requests over healthy instances/pods for scale and availability."),
("AWS", "CloudWatch is mainly for…",
 ["Networking", "Metrics, logs and alarms (observability)", "Storage", "Identity"], 1,
 "CloudWatch collects metrics and logs and can alarm/notify when thresholds are crossed."),
("AWS", "An IAM policy is…",
 ["A network rule", "A JSON document defining allowed/denied actions on resources", "A server", "A subnet"], 1,
 "Policies attach to users/roles/resources and specify permitted actions, resources and conditions."),
("AWS", "Deploying across multiple AZs gives you…",
 ["Lower cost", "Higher availability if one AZ fails", "Faster CPUs", "More storage"], 1,
 "Spreading resources across AZs means a single data-centre failure doesn't take your app down."),
("AWS", "ECR is…",
 ["A database", "A managed container image registry", "A load balancer", "A DNS service"], 1,
 "ECR stores and serves Docker/OCI images, integrating with ECS/EKS and IAM."),
("AWS", "EKS is…",
 ["Serverless functions", "Managed Kubernetes", "Object storage", "A firewall"], 1,
 "EKS runs the Kubernetes control plane for you so you deploy workloads without managing masters."),
("AWS", "Route 53 provides…",
 ["Compute", "DNS (and health checks/routing)", "Storage", "Identity"], 1,
 "Route 53 resolves domain names and can route traffic based on health, latency or geography."),
("AWS", "If you STOP (not terminate) an EC2 instance, its EBS root volume…",
 ["Is deleted", "Persists, so data and config remain when you start it again", "Is emptied", "Moves to S3"], 1,
 "Stopping keeps the EBS volume (you still pay for storage); terminating by default deletes the root volume."),
("AWS", "MFA adds…",
 ["More storage", "A second authentication factor, hardening sign-in", "Faster networking", "A backup"], 1,
 "Multi-factor auth means a stolen password alone isn't enough to sign in — enable it especially on privileged accounts."),
("AWS", "A NAT gateway lets…",
 ["The internet reach private instances", "Private-subnet instances make outbound internet connections without being publicly reachable", "You store files", "You run containers"], 1,
 "It provides outbound-only internet (e.g. for updates) to private subnets while keeping them inaccessible from outside."),
("AWS", "Tagging resources helps mainly with…",
 ["Performance", "Organisation, access control and cost tracking", "Encryption", "Networking"], 1,
 "Consistent tags let you group, filter, control and attribute cost across many resources."),
("AWS", "KMS is used for…",
 ["Load balancing", "Managing encryption keys", "DNS", "Compute"], 1,
 "KMS creates and controls encryption keys used to protect data across AWS services."),
]

TRIVIA = [
("History", "Who is often credited as the first computer programmer?",
 ["Alan Turing", "Ada Lovelace", "Grace Hopper", "Charles Babbage"], 1,
 "Ada Lovelace wrote an algorithm for Babbage's Analytical Engine in the 1840s, earning her that title."),
("Web", "What does HTTP stand for?",
 ["HyperText Transfer Protocol", "High Transfer Text Protocol", "Hyperlink Transmission Process", "Host Transfer Protocol"], 0,
 "HTTP is the protocol browsers and servers use to exchange web pages."),
("Hardware", "How many bits are in a byte?",
 ["4", "8", "16", "10"], 1,
 "A byte is 8 bits, enough to represent 256 distinct values."),
("Software", "Who created the Linux kernel?",
 ["Richard Stallman", "Linus Torvalds", "Ken Thompson", "Dennis Ritchie"], 1,
 "Linus Torvalds released the first Linux kernel in 1991 and still oversees its development."),
("History", "The term 'bug' for a computer fault is linked to a real one — what was it?",
 ["A software worm", "An actual moth found in a relay", "A virus", "A typo"], 1,
 "Grace Hopper's team famously taped a moth into a logbook in 1947 after it jammed a relay."),
("Hardware", "What does CPU stand for?",
 ["Central Processing Unit", "Computer Power Unit", "Central Program Utility", "Core Processing Unit"], 0,
 "The CPU is the main processor that executes instructions."),
("Web", "An HTTP 404 means…",
 ["Server error", "The requested resource was not found", "Unauthorized", "Success"], 1,
 "404 is the classic 'page not found' client error."),
("Software", "The Python language is named after…",
 ["The snake", "Monty Python's Flying Circus", "A person named Python", "A Greek myth"], 1,
 "Guido van Rossum named it after the British comedy troupe, not the reptile."),
("Web", "What does URL stand for?",
 ["Uniform Resource Locator", "Universal Reference Link", "Unified Retrieval Location", "User Resource Label"], 0,
 "A URL is the address that locates a resource on the web."),
("History", "Who is credited with inventing the World Wide Web?",
 ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Vint Cerf"], 1,
 "Tim Berners-Lee proposed and built the Web at CERN around 1989-1991."),
("Hardware", "What does RAM stand for?",
 ["Rapid Access Memory", "Random Access Memory", "Read-Only Access Memory", "Runtime Application Memory"], 1,
 "RAM is fast, volatile working memory the CPU uses while programs run."),
("Software", "What does SQL stand for?",
 ["Structured Query Language", "Sequential Query Logic", "Simple Question Language", "System Query Layer"], 0,
 "SQL is the standard language for querying and managing relational databases."),
("General", "Which base does the binary number system use?",
 ["Base 8", "Base 2", "Base 10", "Base 16"], 1,
 "Binary uses base 2 — just 0 and 1 — which maps directly to on/off in circuits."),
("General", "Hexadecimal is which base?",
 ["Base 2", "Base 16", "Base 8", "Base 10"], 1,
 "Hex is base 16 (0-9 then A-F), a compact way to write binary — one hex digit is 4 bits."),
("Company", "Which company develops the Android operating system?",
 ["Apple", "Google", "Microsoft", "Samsung"], 1,
 "Google leads Android development; phone makers build on it."),
("Company", "Apple was co-founded by Steve Jobs and…",
 ["Bill Gates", "Steve Wozniak", "Jeff Bezos", "Paul Allen"], 1,
 "Steve Wozniak co-founded Apple with Jobs (and Ronald Wayne) in 1976."),
("General", "Moore's Law observes that…",
 ["Software doubles in size yearly", "Transistors per chip roughly double about every two years", "Prices halve monthly", "CPUs run cooler over time"], 1,
 "Gordon Moore noted the transistor-count doubling trend that drove decades of hardware progress."),
("Web", "The default port for HTTPS is…",
 ["80", "443", "22", "8080"], 1,
 "HTTPS uses port 443 by default; plain HTTP uses 80."),
("Hardware", "What does GPU stand for?",
 ["General Processing Unit", "Graphics Processing Unit", "Global Program Unit", "Grid Power Unit"], 1,
 "GPUs excel at parallel work like graphics and, these days, machine learning."),
("Web", "In an email address, the '@' separates…",
 ["Two domains", "The username from the domain", "First and last name", "Protocol from host"], 1,
 "Everything before @ is the local/user part; after it is the domain."),
("General", "What does 'open source' software mean?",
 ["It's free of bugs", "Its source code is publicly available to view, use and modify", "It has no licence", "It runs only on Linux"], 1,
 "Open-source code is published under a licence that permits inspection and modification, e.g. MIT or GPL."),
("General", "What does AI stand for?",
 ["Automated Interface", "Artificial Intelligence", "Applied Informatics", "Adaptive Integration"], 1,
 "AI refers to systems performing tasks that normally need human intelligence."),
("Hardware", "What does USB stand for?",
 ["Universal Serial Bus", "Unified System Board", "Universal Storage Block", "User Serial Buffer"], 0,
 "USB is the ubiquitous standard for connecting peripherals and transferring data/power."),
("Software", "Who created the Git version-control system?",
 ["Guido van Rossum", "Linus Torvalds", "Brendan Eich", "Bjarne Stroustrup"], 1,
 "Linus Torvalds created Git in 2005 to manage Linux kernel development."),
("Web", "What does IP stand for in 'IP address'?",
 ["Internet Protocol", "Internal Path", "Information Packet", "Interface Port"], 0,
 "The Internet Protocol handles addressing and routing of packets across networks."),
("General", "'Debugging' means…",
 ["Writing new features", "Finding and fixing errors in code", "Deleting code", "Deploying software"], 1,
 "Debugging is the process of locating and correcting defects."),
]


ZEN = [
("Security", "Why is AES-GCM generally preferred over AES-CBC for new designs?",
 ["It's faster only", "It provides authenticated encryption (confidentiality + integrity) in one construct", "It uses smaller keys", "It needs no IV"], 1,
 "GCM is an AEAD mode: it detects tampering via an auth tag, whereas CBC gives no integrity and is prone to padding-oracle attacks."),
("Security", "A nonce in AES-GCM must never be reused with the same key because…",
 ["It slows down", "Nonce reuse leaks the XOR of plaintexts and can reveal the auth subkey, breaking confidentiality and integrity", "It corrupts the key", "GCM forbids nonces"], 1,
 "Catastrophic for GCM: repeating (key, nonce) allows forgery of the authentication tag and recovery of plaintext relationships."),
("Security", "In TLS 1.3, forward secrecy is guaranteed because…",
 ["RSA key exchange is mandatory", "Ephemeral (EC)DHE key exchange is used, so past sessions stay safe even if the long-term key leaks", "Sessions are never logged", "Certificates rotate hourly"], 1,
 "TLS 1.3 removed static RSA key transport; ephemeral Diffie-Hellman means compromising the server key later can't decrypt captured past traffic."),
("Security", "What does mutual TLS (mTLS) add over standard TLS?",
 ["Faster handshakes", "The server also verifies the client's certificate, authenticating both parties", "Larger keys", "It removes the CA"], 1,
 "mTLS authenticates the client to the server as well, common for service-to-service auth in zero-trust architectures."),
("Security", "Why store passwords with bcrypt/scrypt/Argon2 rather than SHA-256?",
 ["They're newer", "They're deliberately slow and salted, resisting brute-force and GPU cracking", "They're reversible", "They need no salt"], 2,
 "Fast hashes like SHA-256 are trivially brute-forced; adaptive password hashes add work factor and per-user salt to slow attackers."),
("Security", "In OAuth 2.0 / OIDC, why must a public client (SPA/mobile) use PKCE?",
 ["To speed up login", "To bind the authorization code to the client and stop code-interception attacks", "To avoid HTTPS", "To skip the token endpoint"], 1,
 "PKCE's code_verifier/challenge prevents a stolen authorization code from being redeemed by an attacker, essential without a client secret."),
("Security", "A JWT signed with 'alg: none' is dangerous because…",
 ["It's too large", "If the verifier accepts it, tokens can be forged with no signature", "It expires instantly", "It can't carry claims"], 1,
 "The classic JWT vuln: verifiers must pin expected algorithms and reject 'none' (and not confuse HS256/RS256 key handling)."),
("Security", "The core purpose of threat modeling (e.g. STRIDE) is to…",
 ["Patch faster", "Systematically identify and prioritise threats against a design before building it", "Replace pen-testing", "Encrypt data"], 1,
 "STRIDE (Spoofing, Tampering, Repudiation, Info disclosure, DoS, Elevation) structures reasoning about what can go wrong per component."),
("Security", "In a zero-trust model, network location…",
 ["Grants implicit trust", "Confers no implicit trust — every request is authenticated and authorised on its own merits", "Replaces identity", "Is irrelevant to policy"], 1,
 "Zero trust drops the 'trusted internal network' assumption; identity, device posture and policy gate every access."),
("Security", "Why is a strict Content-Security-Policy an effective XSS mitigation?",
 ["It encrypts the page", "It restricts which script sources can execute, blocking injected inline/third-party scripts", "It hides the DOM", "It signs cookies"], 1,
 "A well-scoped CSP (no unsafe-inline, allow-listed origins) stops most injected scripts from running even if injection occurs."),
("Security", "SSRF is especially dangerous in cloud because an attacker can…",
 ["Delete DNS", "Reach the instance metadata service (e.g. 169.254.169.254) to steal credentials", "Overwrite the CPU", "Bypass TLS"], 1,
 "Server-side request forgery can hit link-local metadata endpoints; IMDSv2's session tokens exist precisely to mitigate this."),
("Security", "The principle of defence in depth means…",
 ["One strong firewall is enough", "Layering independent controls so no single failure is catastrophic", "Encrypting twice", "Trusting the perimeter"], 1,
 "Multiple overlapping controls (network, host, app, identity, data) ensure a single bypass doesn't hand over everything."),
("Security", "Certificate pinning protects against…",
 ["Expired certs", "A malicious or mis-issued CA presenting a valid-looking certificate (MITM)", "Weak passwords", "DoS"], 1,
 "Pinning ties a client to specific keys/certs so a rogue but technically-valid certificate is still rejected — at the cost of rotation complexity."),
("Security", "Why segment an OT/ICS network from IT (as in a Purdue model)?",
 ["Cost", "To contain compromise and keep safety-critical control systems isolated from general IT threats", "Faster PLCs", "Fewer cables"], 1,
 "Segmentation limits lateral movement so an IT breach can't directly reach industrial controllers — critical in manufacturing."),
("Security", "In envelope encryption (e.g. with a KMS), the data key is…",
 ["Stored in plaintext", "Generated per-object and itself encrypted by a master key that never leaves the KMS", "The same as the master key", "Sent to the client unencrypted"], 1,
 "You encrypt data with a local data key, then store that data key wrapped by the KMS master key — enabling scale and key rotation."),
("Security", "A padding oracle attack exploits…",
 ["Weak passwords", "A system that reveals whether decrypted padding is valid, letting an attacker recover plaintext", "Nonce reuse in GCM", "Expired certificates"], 1,
 "Distinguishable padding-error responses on CBC let an attacker decrypt/forge without the key — mitigated by authenticated encryption."),
("Security", "Why prefer short-lived, automatically-rotated credentials over long-lived keys?",
 ["Cheaper", "They shrink the window of exploitation if leaked and reduce blast radius", "They're faster", "They need no policy"], 1,
 "Ephemeral credentials (e.g. STS/role assumption, workload identity) mean a leaked secret is useless quickly."),
("Security", "A confused-deputy problem in cloud IAM occurs when…",
 ["A user forgets a password", "A privileged service is tricked into using its permissions on behalf of an attacker (fixed with external IDs/conditions)", "Two users share a role", "MFA is disabled"], 1,
 "A trusted intermediary misuses its authority for a caller; scoping conditions (like AWS ExternalId) prevent cross-account abuse."),
("Security", "DNSSEC provides…",
 ["Encryption of DNS queries", "Authentication/integrity of DNS records via signatures, preventing spoofing", "Faster lookups", "Ad blocking"], 1,
 "DNSSEC signs records so resolvers can detect forged answers; note it provides integrity, not confidentiality (that's DoH/DoT)."),
("Security", "In an incident, why capture volatile memory before powering off?",
 ["To save disk", "Live memory holds keys, processes and artefacts lost on shutdown — vital for forensics", "It's faster", "To reset logs"], 1,
 "Order-of-volatility: RAM, network state and caches vanish on power-off, so acquire them first to preserve evidence."),
]


ZEN_NIGHTMARE = [
("Side-channel", "Perché un attacco Spectre riesce a leggere memoria che il programma non dovrebbe esporre?",
 ["Sfrutta un buffer overflow nello heap",
  "L'esecuzione speculativa accede a dati oltre un controllo di bounds e lascia tracce nella cache, misurabili via timing anche se il risultato architetturale viene annullato",
  "Rompe AES tramite analisi differenziale",
  "Inietta codice tramite un JWT malformato"], 1,
 "La CPU esegue speculativamente oltre il branch check; il risultato viene scartato a livello architetturale ma lo stato della cache resta, e un timing side-channel lo estrae. Le mitigazioni (retpoline, barriere) hanno un costo prestazionale."),
("Side-channel", "Qual è la differenza chiave tra Meltdown e Spectre?",
 ["Sono lo stesso attacco",
  "Meltdown aggira l'isolamento user/kernel sfruttando l'esecuzione fuori ordine; Spectre induce la vittima a eseguire speculativamente percorsi che rivelano i suoi stessi dati",
  "Meltdown colpisce solo le CPU AMD",
  "Spectre richiede accesso fisico alla macchina"], 1,
 "Meltdown legge memoria kernel dallo spazio utente (mitigato da KPTI); Spectre sfrutta la predizione dei branch per far trapelare dati dal contesto della vittima ed è molto più difficile da eliminare."),
("Hardware", "Su cosa si basa un attacco Rowhammer?",
 ["Sull'overflow di uno stack",
  "Sull'accesso ripetuto e rapido a righe di DRAM che induce bit-flip nelle righe adiacenti per interferenza elettrica",
  "Sul timing della cache L1",
  "Sulla compromissione del bootloader"], 1,
 "Martellando le stesse celle DRAM si provocano bit-flip fisici nelle righe vicine, sfruttabili per privilege escalation. Mitigazioni: ECC e Target Row Refresh, con efficacia parziale."),
("Crypto", "In ECDSA, riusare (o rendere prevedibile) il nonce 'k' tra due firme comporta…",
 ["Nessun problema",
  "Il recupero della chiave privata a partire dalle due firme",
  "Solo una firma più lenta",
  "La rottura della curva ellittica"], 1,
 "Con lo stesso k su messaggi diversi, l'algebra permette di risolvere per la chiave privata: è esattamente il bug che ruppe la sicurezza della PlayStation 3."),
("Crypto", "Perché RSA ed ECC sono considerati a rischio nell'era quantistica?",
 ["Perché le chiavi sono troppo corte",
  "Perché l'algoritmo di Shor, su un computer quantistico sufficientemente grande, fattorizza e risolve il logaritmo discreto in tempo polinomiale",
  "Perché AES li ha sostituiti",
  "Perché il TLS li ha deprecati"], 1,
 "Shor abbatte la difficoltà su cui poggiano RSA (fattorizzazione) ed ECC (log discreto); da qui la corsa alla crittografia post-quantistica."),
("Crypto", "Su quale problema difficile si basa la crittografia lattice-based (es. Kyber)?",
 ["Fattorizzazione di interi",
  "Learning With Errors / problemi sui reticoli come lo Shortest Vector Problem, ritenuti duri anche per i computer quantistici",
  "Logaritmo discreto su curve ellittiche",
  "Collisioni di funzioni hash"], 1,
 "I problemi sui reticoli (LWE, SVP) non hanno un algoritmo quantistico efficiente noto: per questo Kyber e Dilithium sono stati standardizzati come PQC."),
("Crypto", "Cosa si intende con 'harvest now, decrypt later'?",
 ["Un attacco di phishing mirato",
  "Raccogliere oggi traffico cifrato per decifrarlo in futuro, quando i computer quantistici saranno maturi",
  "Un backup incrementale cifrato",
  "Un side-channel sulla cache"], 1,
 "I dati sensibili a lunga vita vanno protetti con PQC già ora, perché il traffico catturato oggi potrà essere decifrato domani."),
("Hardware", "Come può un voltage/clock glitch aiutare a bypassare un secure boot?",
 ["Aumentando la frequenza della CPU",
  "Iniettando un fault preciso che fa saltare un'istruzione (es. il controllo della firma), alterando il flusso di esecuzione",
  "Cancellando la memoria flash",
  "Surriscaldando il chip"], 1,
 "Un glitch mirato può far 'saltare' il branch che verifica la firma, portando il chip a eseguire codice non firmato. Contromisure: doppi controlli e rilevatori di glitch."),
("Crypto", "Perché confrontare un MAC o un token con un normale '==' byte-per-byte è pericoloso?",
 ["È troppo lento",
  "L'uscita anticipata al primo byte diverso crea una differenza di tempo che permette di indovinare il valore byte per byte",
  "Consuma troppa memoria",
  "Non compila"], 1,
 "Un confronto non a tempo costante perde informazione via timing: usa un confronto constant-time (es. hmac.compare_digest o MessageDigest.isEqual dedicato)."),
("Side-channel", "La tecnica Flush+Reload deduce l'attività della vittima…",
 ["Leggendo direttamente la sua RAM",
  "Sfrattando una linea di cache condivisa e misurando se la vittima la ricarica (tempo di accesso), rivelando i suoi accessi in memoria",
  "Modificando il microcodice della CPU",
  "Tramite query DNS"], 1,
 "Su cache condivisa (es. memoria deduplicata) l'attaccante flush-a una linea e misura il reload: veloce = la vittima l'ha ricaricata. Rivela pattern come chiavi in implementazioni non protette."),
("Supply-chain", "L'attacco tipo SolarWinds è insidioso soprattutto perché…",
 ["Ruba password via phishing",
  "Compromette il sistema di build/CI, così il malware viene firmato e distribuito come aggiornamento legittimo del fornitore",
  "Sfrutta una XSS nel portale clienti",
  "Attacca solo Windows Update"], 1,
 "Iniettando codice nella pipeline di build, l'artefatto malevolo eredita firma e fiducia del vendor e raggiunge tutti i clienti: da qui l'enfasi su build integrity e reproducible builds."),
("Supply-chain", "In un attacco di 'dependency confusion', come viene installato il pacchetto malevolo al posto di quello interno?",
 ["Indovinando la password del registry privato",
  "Pubblicando su un registry pubblico un pacchetto con lo stesso nome di uno interno ma versione più alta, e il resolver preferisce quella pubblica",
  "Sfruttando un buffer overflow in npm",
  "Corrompendo il lockfile via MITM"], 1,
 "Se il client interroga sia il registry pubblico sia quello privato senza scoping, vince la versione più alta (pubblica, dell'attaccante). Mitigazioni: scoped/namespace riservati, pinning, priorità esplicita del registry."),
("Supply-chain", "In cosa consiste il typosquatting su un registry di pacchetti?",
 ["Pubblicare versioni più alte di pacchetti interni",
  "Registrare nomi molto simili a pacchetti popolari (es. 'reqests' per 'requests') sperando negli errori di battitura",
  "Rompere la firma del pacchetto",
  "Iniettare voci nel lockfile"], 1,
 "Diverso dalla dependency confusion: qui si punta sull'errore umano di digitazione. Difese: allow-list, verifica dei nomi, tooling che segnala pacchetti sospetti."),
("Supply-chain", "A cosa servono i 'reproducible builds' nella sicurezza della supply chain?",
 ["A compilare più velocemente",
  "A garantire che gli stessi sorgenti producano bit-per-bit lo stesso artefatto, così più parti possono verificare che il binario non sia manomesso",
  "A ridurre la dimensione dell'immagine",
  "A cifrare i sorgenti"], 1,
 "Se il build è deterministico, chiunque può ricompilare e confrontare l'hash con il binario distribuito, smascherando iniezioni nella pipeline."),
("Supply-chain", "Qual è lo scopo principale di un SBOM (Software Bill of Materials)?",
 ["Misurare le prestazioni",
  "Elencare tutti i componenti e le dipendenze di un software, così da valutare rapidamente l'esposizione quando esce una nuova vulnerabilità",
  "Cifrare le dipendenze",
  "Sostituire i test automatici"], 1,
 "Quando esce una CVE (pensa a Log4Shell), un SBOM ti dice subito dove quella libreria è usata, accelerando enormemente la risposta."),
("Hardware", "Un 'cold boot attack' recupera chiavi di cifratura perché…",
 ["La RAM è cifrata di default",
  "La DRAM mantiene i dati per alcuni secondi dopo lo spegnimento (di più se raffreddata), permettendo di leggerne il contenuto, chiavi incluse",
  "Le chiavi sono salvate nel BIOS",
  "Sfrutta un timing sulla cache"], 1,
 "La memoria non svanisce all'istante; raffreddandola e ri-bootando su un tool si estraggono chiavi di full-disk encryption. Contromisure: chiavi in enclave, scrubbing della RAM."),
("Threat", "Un 'evil maid attack' contro il full-disk encryption sfrutta…",
 ["Una debolezza matematica di AES",
  "L'accesso fisico non sorvegliato al dispositivo per manomettere bootloader/firmware e catturare la passphrase al boot successivo",
  "Un padding oracle sul disco",
  "Il riuso del nonce in GCM"], 1,
 "Con accesso fisico ripetuto (tipico di una stanza d'albergo) si impianta un bootloader malevolo che registra la passphrase. Difese: secure boot verificato, sigilli anti-manomissione, measured boot con TPM."),
("Crypto", "Perché le implementazioni RSA serie usano il 'blinding'?",
 ["Per accorciare le chiavi",
  "Per randomizzare l'input dell'operazione privata e neutralizzare i timing/side-channel attack sulla chiave",
  "Per comprimere il ciphertext",
  "Per evitare il padding"], 1,
 "Il blinding moltiplica per un fattore casuale prima dell'esponenziazione privata, scorrelando tempo e consumo dal segreto e vanificando i side-channel a tempo."),
]


def to_questions(rows):
    out = []
    for i, (topic, text, options, correct, expl) in enumerate(rows, start=1):
        assert len(options) == 4 and 0 <= correct <= 3, f"bad row {i}"
        # Shuffle options deterministically (seeded per question) to avoid
        # answer-position bias — otherwise the correct answer is always 'B'.
        rng = random.Random(text)
        order = [0, 1, 2, 3]
        rng.shuffle(order)
        options = [options[j] for j in order]
        correct = order.index(correct)
        out.append({"id": f"q{i:03d}", "topic": topic, "text": text,
                    "options": options, "correct": correct, "explanation": expl})
    return out


def write_set(fid, name, description, order, questions):
    path = os.path.join(QDIR, fid + ".json")
    payload = {"id": fid, "name": name, "description": description, "order": order,
               "questions": questions}
    with open(path, "w") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"  {fid}: {len(questions)} questions -> {name}")


print("Building question sets:")
write_set("java-devops-core", "Java & DevOps · Core",
          "Graduate-level Java & DevOps. Practical, reasoning-based questions.",
          1, load_core_questions())
write_set("java-devops-advanced", "Java & DevOps · Advanced",
          "Harder Java & DevOps for experienced hires — concurrency, JVM internals, Kubernetes, IaC.",
          2, to_questions(ADVANCED))
write_set("ai-foundations", "AI Foundations · Beginner",
          "AI & machine-learning basics for beginners — no experience needed.",
          3, to_questions(AI))
write_set("git-workflow", "Git & Workflow",
          "Branching, merges, PRs and everyday version-control workflow.",
          4, to_questions(GIT))
write_set("linux-cli", "Linux & Command Line",
          "Shell essentials: permissions, processes, pipes, logs and networking basics.",
          5, to_questions(LINUX))
write_set("aws-fundamentals", "AWS Fundamentals",
          "Core AWS: IAM, VPC, EC2/S3, regions/AZs and the shared responsibility model.",
          6, to_questions(AWS))
write_set("tech-trivia", "General Tech Trivia",
          "Lighter round — computing history, web, hardware and general tech knowledge.",
          7, to_questions(TRIVIA))
write_set("zen-expert", "Zen · Expert",
          "Deep cybersecurity, cryptography and cloud/network security. For Guido. Not easy.",
          8, to_questions(ZEN))
write_set("zen-nightmare", "Zen · Nightmare (IT)",
          "Incubo per Guido, in italiano: side-channel, post-quantum, supply-chain, fault injection.",
          9, to_questions(ZEN_NIGHTMARE))
print("Done.")
